server :
  port : 8081

spring :
  application:
    name : talko

  config :
    import : application-secret.yml
    activate:
      on-profile : local

  datasource:
    url: jdbc:mysql://localhost:3308/talko
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}